# Generated by Django 6.0.6 on 2026-06-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True, max_length=300)),
                ('portfolio_url', models.URLField(blank=True, max_length=300)),
                ('resume_url', models.URLField(blank=True, max_length=300)),
                ('theme', models.CharField(choices=[('professional_blue', 'Professional Blue'), ('executive_dark', 'Executive Dark'), ('modern_purple', 'Modern Purple')], default='professional_blue', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('offline_qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('online_qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('hybrid_qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('png_file', models.ImageField(blank=True, null=True, upload_to='pngs/')),
                ('vcf_file', models.FileField(blank=True, null=True, upload_to='vcfs/')),
                ('profile_views', models.IntegerField(default=0)),
                ('qr_scans', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Profile View'), ('scan', 'QR Scan'), ('download', 'Asset Download')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_logs', to='cards.digitalcard')),
            ],
        ),
    ]
