# Generated by Django 6.0.6 on 2026-06-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='paid_tier',
            field=models.CharField(choices=[('silver', 'Silver (15 Rs)'), ('gold', 'Gold (20 Rs)'), ('platinum', 'Platinum (40 Rs)')], default='silver', max_length=20),
        ),
    ]
